log_level: INFO

db_name: edaphobase
db_user: postgres
db_password: ~
db_host: postgres  # Docker service name
db_port: 5432

rdi: edaphobase
rdi_url: https://edaphobase.org
max_concurrent_arc_builds: 12

api_client:
  # NOTE: Change this to the external Middleware API URL
  api_url: "https://middleware.fairagro.net"
  timeout: 600
  client_cert_path: "/etc/sql_to_arc/client.crt"
  client_key_path: "/run/secrets/client.key"
  verify_ssl: true

otel:
  log_console_spans: false
