log_level: DEBUG

csw_url: "https://repository-e.dataservice.zalf.de/catalogue/csw"
rdi: "bonares"
query: ~
xml_request: ~

api_client:
  api_url: "https://middleware.fairagro.net"
  timeout: 60.0
  client_cert_path: "/workspaces/m4.2_inspire_to_arc-vscode/dev_environment/client.crt"
  client_key_path: "/workspaces/m4.2_inspire_to_arc-vscode/dev_environment/client.decrypted.key"
  verify_ssl: true
  max_retries: 3
  retry_backoff_factor: 1.0
